//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Music.cpp
//  @ Date : 09.04.18
//  @ Author :
//
//


#include "Music.h"

Music::Music(string caption, string compositor) :
    caption(caption), compositor(compositor)
{

}

string Music::getCaption()
{
    return this->caption;
}

string Music::getCompositor()
{
    return this->compositor;
}

void Music::show()
{
    cout << "Caption: " << this->caption << '\n';
    cout << "Compositor: " << this->compositor << '\n';
}

