//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Music.h
//  @ Date : 09.04.18
//  @ Author :
//
//


#if !defined(_MUSIC_H)
#define _MUSIC_H

#include <iostream>
#include <string>
using namespace std;

class Music
{
public:
    Music(string caption, string compositor);
    string getCaption();
    string getCompositor();
    virtual void show();

private:
    string caption;
    string compositor;
};

#endif  //_MUSIC_H
