//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Song.cpp
//  @ Date : 09.04.18
//  @ Author :
//
//


#include "Song.h"

Song::Song(string caption, string compositor, string poem) :
    poem(poem), Music(caption, compositor)
{

}

string Song::getPoem()
{
    return this->poem;
}

void Song::show()
{
    Music::show();
    cout << "Poem: " << this->poem << '\n';
}

